global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

scrape_configs:
  - job_name: rabbitmq
    scrape_interval: 10s
    static_configs:
      - targets:
          - bench-rabbitmq:15692
